### ISSUE TITLE
About bilateral_slice

### ISSUE THREAD

**Issue by woojoo520** [EricElmoznino/deep_bilateral_network#4]
Sorry, I have sone problem installing setup.py. I dont't know why? 

bilateral_slice.cpp(85): error C2059: 语法错误:“do”
bilateral_slice.cpp(88): error C2143: 语法错误: 缺少“;”(在“{”的前面)
bilateral_slice.cpp(88): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
bilateral_slice.cpp(85): error C2059: 语法错误:“while”
bilateral_slice.cpp(89): error C2059: 语法错误:“do”
bilateral_slice.cpp(89): error C2143: 语法错误: 缺少“;”(在“{”的前面)
bilateral_slice.cpp(89): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
bilateral_slice.cpp(89): error C2059: 语法错误:“while”
bilateral_slice.cpp(92): error C2059: 语法错误:“if”
bilateral_slice.cpp(92): error C2143: 语法错误: 缺少“;”(在“{”的前面)
bilateral_slice.cpp(92): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
bilateral_slice.cpp(97): error C2059: 语法错误:“else”
bilateral_slice.cpp(97): error C2143: 语法错误: 缺少“;”(在“{”的前面)
bilateral_slice.cpp(97): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
bilateral_slice.cpp(104): error C2065: “bs”: 未声明的标识符
bilateral_slice.cpp(104): error C2065: “h”: 未声明的标识符
bilateral_slice.cpp(104): error C2065: “w”: 未声明的标识符
bilateral_slice.cpp(105): error C2065: “input”: 未声明的标识符
bilateral_slice.cpp(108): error C2059: 语法错误:“return”
bilateral_slice.cpp(122): error C2059: 语法错误:“}”
bilateral_slice.cpp(122): error C2143: 语法错误: 缺少“;”(在“}”的前面)
bilateral_slice.cpp(130): error C2143: 语法错误: 缺少“;”(在“{”的前面)
bilateral_slice.cpp(130): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
bilateral_slice.cpp(182): error C2065: “bilateral_slice_backward”: 未声明的标识符

**Comment by EricElmoznino** [comment]
Not sure what the issue is and can’t read the errors. The layer installation works on my Mac and several Linux servers, but are for me to debug why it might not be working in any one case.

**Comment by ewen1024** [comment]
For me, it works fine on ubuntu but failed right now on Windows
running install_lib
running build_ext
C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'bilateral_slice' extension
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release
Emitting ninja build file D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...


Traceback (most recent call last):
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 124, in <module>
    'build_ext': BuildExtension
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install    self.run_command('bdist_egg')
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command    self.run_command(cmdname)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by ewen1024** [comment]
as for why i want to transfer to windows for the try,  my ubuntu system ran into  '  unable to load "dataset" defined in configuration.py'

**Comment by ewen1024** [comment]
after linking cl.exe to the enviroment and modified the cpp_extension file   1.gbk format  2. ninja --version, the program ran as far as   
(hdr) D:\project\deep_bilateral_network-master\bilateral_slice_op>python setup.py install
running install
running bdist_egg
running egg_info
creating bilateral_slice_op.egg-info
writing bilateral_slice_op.egg-info\PKG-INFO
writing dependency_links to bilateral_slice_op.egg-info\dependency_links.txt
writing top-level names to bilateral_slice_op.egg-info\top_level.txt
writing manifest file 'bilateral_slice_op.egg-info\SOURCES.txt'
reading manifest file 'bilateral_slice_op.egg-info\SOURCES.txt'
writing manifest file 'bilateral_slice_op.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'bilateral_slice' extension
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release
Emitting ninja build file D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.9.0
creating D:\project\deep_bilateral_network-master\bilateral_slice_op\build\lib.win-amd64-3.6
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\sorrow\anaconda3\envs\hdr\lib\site-packages\torch\lib /LIBPATH:C:\Users\sorrow\anaconda3\envs\hdr\libs /LIBPATH:C:\Users\sorrow\anaconda3\envs\hdr\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_bilateral_slice D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\bilateral_slice.obj D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\bilateral_slice_cpu.obj /OUT:build\lib.win-amd64-3.6\bilateral_slice.cp36-win_amd64.pyd /IMPLIB:D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\bilateral_slice.cp36-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\bilateral_slice.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181




~~~D:\project\deep_bilateral_network-master\bilateral_slice_op\build\temp.win-amd64-3.6\Release\bilateral_slice.obj ~~~           there is no such file in this folder, so i don't know what's going wrong right now.
